source "https://rubygems.org"

gem 'repository-manager', :path => '../../'
gem 'factory_bot'
gem 'paper_trail'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem "sqlite3", :platform => [:ruby, :mswin, :mingw]
gem "jdbc-sqlite3", :platform => :jruby

group :development, :test do
  gem 'railroady'
end
